kind: pipeline
type: docker
name: default

steps:
- name: test
  image: theprincemax/compil-tester:latest
  environment:
    TEST_FOLDER: "tests"
  commands:
    - "cd /app && ./test.sh"
  volumes:
  - name: workspace
    path: /app

